language: node_js

node_js:
  - 6
  - 7
  - 8
  - 9

php:
  - 7.0

sudo: false

os:
  - osx
  - linux

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - cd server/tests/fixtures/project;composer install --no-interaction --prefer-dist --no-suggest;
  - npm install

script:
  - npm test --silent